name: FastPack CI
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [win-x64, linux-x64, osx-x64]
    runs-on: windows-latest
    steps:
      - name: Checkout for ${{ matrix.os }}
        uses: actions/checkout@v5
      - name: Setup dotnet for ${{ matrix.os }}
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
      - name: Build ${{ matrix.os }}
        run: dotnet publish -r ${{ matrix.os }} -c Release -o output/${{ matrix.os }} --verbosity q --self-contained True -p:PublishTrimmed=True -p:IncludeNativeLibrariesForSelfExtract=True -p:EnableCompressionInSingleFile=True ./src/FastPack/FastPack.csproj
      - name: Upload artifacts for ${{ matrix.os }}
        uses: actions/upload-artifact@v5
        with:
          name: FastPack executable ${{ matrix.os }}
          path: |
            output/**/*

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # , macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout for ${{ matrix.os }}
        uses: actions/checkout@v5
      - name: Setup dotnet for ${{ matrix.os }}
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
      - name: Install dependencies for ${{ matrix.os }}
        run: dotnet restore
      - name: Test for ${{ matrix.os }}
        run: dotnet test --no-restore --verbosity normal
